pipeline:
  build:
    image: plugins/docker
    settings:
      repo: denperidge/semantic.works
      tags: latest
    secrets: [ docker_username, docker_password ]
when:
  branch: master
  event: push
